package com.example.learnsphere.ui.theme

import androidx.compose.ui.graphics.Color

//val Purple80 = Color(0xFFD0BCFF)
//val PurpleGrey80 = Color(0xFFCCC2DC)
//val Pink80 = Color(0xFFEFB8C8)
//
//val Purple40 = Color(0xFF6650a4)
//val PurpleGrey40 = Color(0xFF625b71)
//val Pink40 = Color(0xFF7D5260)
//
//val TruePurple = Color(0xFF6A1B9A)
//val Violet = Color(0xFF8E24AA)
//val Orchid = Color(0xFF9C27B0)
//val MediumPurple = Color(0xFFAB47BC)
//val PalePurple = Color(0xFFBA68C8)
//val LightPurple = Color(0xFF9575CD)


val md_theme_light_primary = Color(0xFF5A4BC4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE4DFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF170066)
val md_theme_light_secondary = Color(0xFF984061)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF3E001D)
val md_theme_light_tertiary = Color(0xFF006B55)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF42FED0)
val md_theme_light_onTertiaryContainer = Color(0xFF002018)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF3F0016)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF3F0016)
val md_theme_light_surfaceVariant = Color(0xFFE5E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
val md_theme_light_outline = Color(0xFF787680)
val md_theme_light_inverseOnSurface = Color(0xFFFFECEE)
val md_theme_light_inverseSurface = Color(0xFF5F112A)
val md_theme_light_inversePrimary = Color(0xFFC6BFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5A4BC4)
val md_theme_light_outlineVariant = Color(0xFFC9C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC6BFFF)
val md_theme_dark_onPrimary = Color(0xFF2A0E96)
val md_theme_dark_primaryContainer = Color(0xFF4230AB)
val md_theme_dark_onPrimaryContainer = Color(0xFFE4DFFF)
val md_theme_dark_secondary = Color(0xFFFFB1C8)
val md_theme_dark_onSecondary = Color(0xFF5E1133)
val md_theme_dark_secondaryContainer = Color(0xFF7B2949)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_tertiary = Color(0xFF00E0B5)
val md_theme_dark_onTertiary = Color(0xFF00382B)
val md_theme_dark_tertiaryContainer = Color(0xFF005140)
val md_theme_dark_onTertiaryContainer = Color(0xFF42FED0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF3F0016)
val md_theme_dark_onBackground = Color(0xFFFFD9DF)
val md_theme_dark_surface = Color(0xFF3F0016)
val md_theme_dark_onSurface = Color(0xFFFFD9DF)
val md_theme_dark_surfaceVariant = Color(0xFF47464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val md_theme_dark_outline = Color(0xFF928F99)
val md_theme_dark_inverseOnSurface = Color(0xFF3F0016)
val md_theme_dark_inverseSurface = Color(0xFFFFD9DF)
val md_theme_dark_inversePrimary = Color(0xFF5A4BC4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC6BFFF)
val md_theme_dark_outlineVariant = Color(0xFF47464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF6153CC)
val CustomColor1 = Color(0xFFA60067)
val light_CustomColor1 = Color(0xFFB31571)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFD9E5)
val light_onCustomColor1Container = Color(0xFF3D0023)
val dark_CustomColor1 = Color(0xFFFFB0CF)
val dark_onCustomColor1 = Color(0xFF63003C)
val dark_CustomColor1Container = Color(0xFF8C0056)
val dark_onCustomColor1Container = Color(0xFFFFD9E5)
